/* Generated By:JavaCC: Do not edit this line. compilador.java */
import java.io.*;
import java.util.*;
import java.util.ArrayList;
import java.util.List;


class compilador implements compiladorConstants {




        public static void main( String[] args )throws ParseException, Exception
        {
                try
                {
                compilador analizador = new compilador( System.in ) ;
                        analizador.Programa();
                        System.out.println("\u005ctFinalizado con exito.");
                }
                catch(ParseException e)
                {
                        System.out.println(e.getMessage());
                        System.out.println("\u005ctError.");
                }

        }

//1. namespace
  static final public void Programa() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LIBRERIAS:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      librerias();
    }
    jj_consume_token(NAMESPACE);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(DOSPUNTOS);
    programaPrincipal();
    jj_consume_token(FIN);
    jj_consume_token(0);
  }

//2. librerias
  static final public void librerias() throws ParseException {
    jj_consume_token(LIBRERIAS);
    jj_consume_token(USO_LIBRERIA);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUNTO:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      jj_consume_token(PUNTO);
      jj_consume_token(USO_LIBRERIA);
    }
  }

//3.Programa principal (class program)
  static final public void programaPrincipal() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PROGRAMA:
      jj_consume_token(PROGRAMA);
      jj_consume_token(DEFINE_CLASES);
      jj_consume_token(DOSPUNTOS);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case TIPO_DATO:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_3;
        }
        declaracionVariable();
      }
      metodoPrincipal();
      jj_consume_token(FIN);
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOSPUNTOS:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        defineClase();
        break;
      case DOSPUNTOS:
        herencia();
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

//4. Metodo main
  static final public void metodoPrincipal() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAIN:
      jj_consume_token(MAIN);
      jj_consume_token(DOSPUNTOS);
      bloqueCodigoMetodo();
      jj_consume_token(FIN);
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
      case FUNCION:
      case MODIFICADOR_ACCESO:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
      case MODIFICADOR_ACCESO:
        defineMetodos();
        break;
      case FUNCION:
        defineFuncion();
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void bloqueCodigoMetodo() throws ParseException {
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PRINT:
      case TRY:
      case TIPO_DATO:
      case PARIZQ:
      case CORIZQ:
      case LLAVEIZQ:
      case EXTENDS:
      case CICLOWHILE:
      case FOR:
      case DO:
      case OBJECTOS:
      case SWITCH:
      case IF:
      case TERMINA:
      case MAYUSCULA:
      case MINUSCULA:
      case TYPEOF:
      case SIZEOF:
      case SET:
      case GET:
      case RANGE:
      case SISTEMA:
      case MATEMATICA:
      case READ:
      case CONVERTIR:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PRINT:
        imprime();
        break;
      case TIPO_DATO:
        declaracionVariable();
        break;
      case CICLOWHILE:
      case FOR:
      case DO:
        ciclos();
        break;
      case TRY:
        excepciones();
        break;
      case IF:
        preguntaIf();
        break;
      case OBJECTOS:
        objeto();
        break;
      case EXTENDS:
        thiss();
        break;
      case IDENTIFIER:
        llamadaMetodo();
        break;
      case SET:
        sett();
        break;
      case GET:
        gett();
        break;
      case TERMINA:
        salir();
        break;
      case SISTEMA:
        limpiar();
        break;
      case MATEMATICA:
        operacionMatematica();
        break;
      case PARIZQ:
      case LLAVEIZQ:
        contieneElementos();
        break;
      case RANGE:
        rango();
        break;
      case CORIZQ:
        matriz();
        break;
      case SWITCH:
        preguntaSwitch();
        break;
      case READ:
        leer();
        break;
      case SIZEOF:
        numeroBytes();
        break;
      case TYPEOF:
        tipoOperador();
        break;
      case CONVERTIR:
        convertir();
        break;
      case MAYUSCULA:
      case MINUSCULA:
        may_min();
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

//5. Declaración de variables
  static final public void declaracionVariable() throws ParseException {
    jj_consume_token(TIPO_DATO);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(ASIGNACION);
    valor();
  }

  static final public void valor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    case NUMEROS:
      jj_consume_token(NUMEROS);
      break;
    case CADENA:
      jj_consume_token(CADENA);
      break;
    case CARAC:
      jj_consume_token(CARAC);
      break;
    case NUMEROS_DECIMALES:
      jj_consume_token(NUMEROS_DECIMALES);
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//6. Pregunta IF
  static final public void preguntaIf() throws ParseException {
    jj_consume_token(IF);
    condicion();
    jj_consume_token(DOSPUNTOS);
    bloqueCodigo();
    jj_consume_token(FIN);
    sinoSi();
    sino();
  }

  static final public void sinoSi() throws ParseException {
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELIF:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_7;
      }
      jj_consume_token(ELIF);
      condicion();
      jj_consume_token(DOSPUNTOS);
      bloqueCodigo();
      jj_consume_token(FIN);
    }
  }

  static final public void sino() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      jj_consume_token(DOSPUNTOS);
      bloqueCodigo();
      jj_consume_token(FIN);
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
  }

  static final public void condicion() throws ParseException {
    valor();
    jj_consume_token(OP_REL);
    valor();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OP_LOG:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_8;
      }
      jj_consume_token(OP_LOG);
      valor();
      jj_consume_token(OP_REL);
      valor();
    }
  }

//7. Imprimir
  static final public void imprime() throws ParseException {
    jj_consume_token(PRINT);
    jj_consume_token(PARIZQ);
    imprimeValor();
    jj_consume_token(PARDER);
  }

  static final public void imprimeValor() throws ParseException {
    valor();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAS:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_9;
      }
      jj_consume_token(MAS);
      valor();
    }
  }

// 8. Switch case
  static final public void preguntaSwitch() throws ParseException {
    jj_consume_token(SWITCH);
    jj_consume_token(PARIZQ);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(PARDER);
    jj_consume_token(DOSPUNTOS);
    casos();
    porDefecto();
    jj_consume_token(FIN);
  }

  static final public void casos() throws ParseException {
    label_10:
    while (true) {
      jj_consume_token(CASE);
      valor();
      jj_consume_token(DOSPUNTOS);
      bloqueCodigo();
      jj_consume_token(INTERRUPTOR);
      jj_consume_token(FIN);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CASE:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_10;
      }
    }
  }

  static final public void porDefecto() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PORDEFECTO:
      jj_consume_token(PORDEFECTO);
      jj_consume_token(DOSPUNTOS);
      bloqueCodigo();
      jj_consume_token(FIN);
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
  }

//9. ciclos
  static final public void ciclos() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CICLOWHILE:
      cicloWhile();
      break;
    case FOR:
      cicloFor();
      break;
    case DO:
      cicloDo();
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void cicloWhile() throws ParseException {
    jj_consume_token(CICLOWHILE);
    condicion();
    jj_consume_token(DOSPUNTOS);
    bloqueCodigo();
    jj_consume_token(FIN);
  }

  static final public void cicloFor() throws ParseException {
    jj_consume_token(FOR);
    inicializador();
    jj_consume_token(ASIGNACION);
    jj_consume_token(NUMEROS);
    jj_consume_token(PUNTOYCOMA);
    condicion();
    jj_consume_token(PUNTOYCOMA);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(INC_DEC);
    jj_consume_token(DOSPUNTOS);
    bloqueCodigo();
    jj_consume_token(FIN);
  }

  static final public void inicializador() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIPO_DATO:
      jj_consume_token(TIPO_DATO);
      jj_consume_token(IDENTIFIER);
      break;
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void cicloDo() throws ParseException {
    jj_consume_token(DO);
    jj_consume_token(DOSPUNTOS);
    bloqueCodigo();
    jj_consume_token(FIN);
    jj_consume_token(PARIZQ);
    jj_consume_token(CICLOWHILE);
    condicion();
    jj_consume_token(PARDER);
  }

  static final public void bloqueCodigo() throws ParseException {
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PRINT:
      case TRY:
      case TIPO_DATO:
      case PARIZQ:
      case CORIZQ:
      case LLAVEIZQ:
      case CICLOWHILE:
      case FOR:
      case DO:
      case IF:
      case TERMINA:
      case MAYUSCULA:
      case MINUSCULA:
      case RANGE:
      case SISTEMA:
      case MATEMATICA:
      case CONVERTIR:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIPO_DATO:
        declaracionVariable();
        break;
      case CICLOWHILE:
      case FOR:
      case DO:
        ciclos();
        break;
      case PRINT:
        imprime();
        break;
      case IF:
        preguntaIf();
        break;
      case PARIZQ:
      case LLAVEIZQ:
        contieneElementos();
        break;
      case MATEMATICA:
        operacionMatematica();
        break;
      case TRY:
        excepciones();
        break;
      case TERMINA:
        salir();
        break;
      case SISTEMA:
        limpiar();
        break;
      case RANGE:
        rango();
        break;
      case CORIZQ:
        matriz();
        break;
      case IDENTIFIER:
        inc_dec();
        break;
      case CONVERTIR:
        convertir();
        break;
      case MAYUSCULA:
      case MINUSCULA:
        may_min();
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

//10. Funcion
  static final public void defineFuncion() throws ParseException {
    jj_consume_token(FUNCION);
    jj_consume_token(PARIZQ);
    defineParametros();
    jj_consume_token(PARDER);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(DOSPUNTOS);
    bloqueCodigoMetodo();
    jj_consume_token(FIN);
  }

  static final public void defineParametros() throws ParseException {
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIPO_DATO:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_12;
      }
      defineParametro();
      label_13:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMA:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_13;
        }
        jj_consume_token(COMA);
        defineParametro();
      }
    }
  }

  static final public void defineParametro() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIPO_DATO:
      jj_consume_token(TIPO_DATO);
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    jj_consume_token(IDENTIFIER);
  }

//11. Excepcion try-catch
  static final public void excepciones() throws ParseException {
    jj_consume_token(TRY);
    jj_consume_token(DOSPUNTOS);
    bloqueCodigo();
    jj_consume_token(FIN);
    jj_consume_token(MANDA_EXCEPCION);
    jj_consume_token(PARIZQ);
    jj_consume_token(PARDER);
    jj_consume_token(DOSPUNTOS);
    imprime();
    jj_consume_token(FIN);
  }

//12. Define clase
  static final public void defineClase() throws ParseException {
    jj_consume_token(IDENTIFIER);
    jj_consume_token(MODIFICADOR_ACCESO);
    jj_consume_token(DEFINE_CLASES);
    jj_consume_token(DOSPUNTOS);
    bloqueCodigoClase();
    jj_consume_token(FIN);
  }

  static final public void bloqueCodigoClase() throws ParseException {
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
      case TIPO_DATO:
      case PARIZQ:
      case CORIZQ:
      case LLAVEIZQ:
      case FUNCION:
      case MODIFICADOR_ACCESO:
      case SET:
      case GET:
        ;
        break;
      default:
        jj_la1[25] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FUNCION:
        defineFuncion();
        break;
      case VOID:
      case MODIFICADOR_ACCESO:
        defineMetodos();
        break;
      case SET:
        sett();
        break;
      case GET:
        gett();
        break;
      case PARIZQ:
      case LLAVEIZQ:
        contieneElementos();
        break;
      case TIPO_DATO:
        declaracionVariable();
        break;
      case CORIZQ:
        matriz();
        break;
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

//13. Objeto
  static final public void objeto() throws ParseException {
    jj_consume_token(OBJECTOS);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(ASIGNACION);
    jj_consume_token(OPERADOR);
    jj_consume_token(OBJECTOS);
    jj_consume_token(PARIZQ);
    jj_consume_token(PARDER);
  }

// 14. contiene elentos (listas y arreglos)
  static final public void contieneElementos() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LLAVEIZQ:
      lista();
      break;
    case PARIZQ:
      arreglo();
      break;
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void lista() throws ParseException {
    jj_consume_token(LLAVEIZQ);
    elementosContenidos();
    jj_consume_token(LLAVEDER);
    jj_consume_token(ASIGNACION);
    inicializador();
  }

  static final public void elementoContenido() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CADENA:
      jj_consume_token(CADENA);
      break;
    case NUMEROS:
      jj_consume_token(NUMEROS);
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void elementosContenidos() throws ParseException {
    elementoContenido();
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMA:
        ;
        break;
      default:
        jj_la1[29] = jj_gen;
        break label_15;
      }
      jj_consume_token(COMA);
      elementoContenido();
    }
  }

  static final public void arreglo() throws ParseException {
    jj_consume_token(PARIZQ);
    elementosContenidos();
    jj_consume_token(PARDER);
    jj_consume_token(ASIGNACION);
    inicializador();
    jj_consume_token(CORIZQ);
    jj_consume_token(NUMEROS);
    jj_consume_token(CORDER);
  }

//15. retorn
  static final public void retorno() throws ParseException {
    jj_consume_token(RETORNA_VALOR);
    jj_consume_token(IDENTIFIER);
  }

//16. leer
  static final public void leer() throws ParseException {
    jj_consume_token(READ);
    jj_consume_token(PUNTO);
    jj_consume_token(OPERADOR);
    jj_consume_token(READ);
    jj_consume_token(PARIZQ);
    jj_consume_token(PARDER);
  }

//17. rango
  static final public void rango() throws ParseException {
    jj_consume_token(RANGE);
    jj_consume_token(PARIZQ);
    dentroRango();
    jj_consume_token(PARDER);
  }

  static final public void dentroRango() throws ParseException {
    jj_consume_token(NUMEROS);
    jj_consume_token(COMA);
    jj_consume_token(NUMEROS);
  }

//18. size of
  static final public void numeroBytes() throws ParseException {
    jj_consume_token(SIZEOF);
    jj_consume_token(PARIZQ);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIPO_DATO:
      jj_consume_token(TIPO_DATO);
      break;
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PARDER);
  }

//19. type of
  static final public void tipoOperador() throws ParseException {
    jj_consume_token(TYPEOF);
    jj_consume_token(IDENTIFIER);
  }

//20. this
  static final public void thiss() throws ParseException {
    jj_consume_token(EXTENDS);
    jj_consume_token(PUNTO);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(ASIGNACION);
    jj_consume_token(IDENTIFIER);
  }

// 21. exit
  static final public void salir() throws ParseException {
    jj_consume_token(TERMINA);
    jj_consume_token(PARIZQ);
    jj_consume_token(PARDER);
  }

// 22. llama metodo
  static final public void llamadaMetodo() throws ParseException {
    jj_consume_token(IDENTIFIER);
    jj_consume_token(PARIZQ);
    defineParametros();
    jj_consume_token(PARDER);
  }

//23. herencia
  static final public void herencia() throws ParseException {
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(DEFINE_CLASES);
    jj_consume_token(DOSPUNTOS);
    bloqueCodigoClase();
    jj_consume_token(FIN);
  }

//24. set
  static final public void sett() throws ParseException {
    jj_consume_token(SET);
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(ASIGNACION);
    valor();
    jj_consume_token(FIN);
  }

//25. get
  static final public void gett() throws ParseException {
    jj_consume_token(GET);
    jj_consume_token(DOSPUNTOS);
    retorno();
    jj_consume_token(FIN);
  }

//26. matrices
  static final public void matriz() throws ParseException {
    jj_consume_token(CORIZQ);
    jj_consume_token(NUMEROS);
    jj_consume_token(COMA);
    jj_consume_token(NUMEROS);
    jj_consume_token(CORDER);
    inicializador();
    jj_consume_token(ASIGNACION);
    jj_consume_token(OPERADOR);
    jj_consume_token(TIPO_DATO);
    jj_consume_token(CORIZQ);
    elementosMatriz();
    jj_consume_token(CORDER);
  }

  static final public void elementosMatriz() throws ParseException {
    jj_consume_token(LLAVEIZQ);
    elementosContenidos();
    jj_consume_token(LLAVEDER);
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMA:
        ;
        break;
      default:
        jj_la1[31] = jj_gen;
        break label_16;
      }
      jj_consume_token(COMA);
      jj_consume_token(LLAVEIZQ);
      elementosContenidos();
      jj_consume_token(LLAVEDER);
    }
  }

//27. limpiar
  static final public void limpiar() throws ParseException {
    jj_consume_token(SISTEMA);
    jj_consume_token(PUNTO);
    jj_consume_token(LIMPIAR);
  }

//28. math
  static final public void operacionMatematica() throws ParseException {
    jj_consume_token(MATEMATICA);
    jj_consume_token(PUNTO);
    jj_consume_token(FUNCMATEMATICA);
    jj_consume_token(PARIZQ);
    valorOperacion();
    jj_consume_token(PARDER);
  }

  static final public void valorOperacion() throws ParseException {
    valorOper();
    label_17:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMA:
        ;
        break;
      default:
        jj_la1[32] = jj_gen;
        break label_17;
      }
      jj_consume_token(COMA);
      valorOper();
    }
  }

  static final public void valorOper() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    case NUMEROS:
      jj_consume_token(NUMEROS);
      break;
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//30. definir metodos
  static final public void defineMetodos() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MODIFICADOR_ACCESO:
      metodoRetorno();
      break;
    case VOID:
      metodoSinRetorno();
      break;
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void metodoRetorno() throws ParseException {
    jj_consume_token(MODIFICADOR_ACCESO);
    jj_consume_token(TIPO_DATO);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(PARIZQ);
    defineParametros();
    jj_consume_token(PARDER);
    jj_consume_token(DOSPUNTOS);
    bloqueCodigoMetodo();
    retorno();
    jj_consume_token(FIN);
  }

  static final public void metodoSinRetorno() throws ParseException {
    jj_consume_token(VOID);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(PARIZQ);
    defineParametros();
    jj_consume_token(PARDER);
    jj_consume_token(DOSPUNTOS);
    bloqueCodigoMetodo();
    jj_consume_token(FIN);
  }

  static final public void inc_dec() throws ParseException {
    jj_consume_token(IDENTIFIER);
    jj_consume_token(INC_DEC);
  }

//31. Convierte
  static final public void convertir() throws ParseException {
    jj_consume_token(CONVERTIR);
    jj_consume_token(PARIZQ);
    jj_consume_token(TIPO_DATO);
    jj_consume_token(PARIZQ);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(PARDER);
    jj_consume_token(PARDER);
    jj_consume_token(ASIGNACION);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIPO_DATO:
      jj_consume_token(TIPO_DATO);
      break;
    default:
      jj_la1[35] = jj_gen;
      ;
    }
    jj_consume_token(IDENTIFIER);
  }

//32. mayuscula y MINUSCULA
  static final public void may_min() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUSCULA:
      convMinuscula();
      break;
    case MAYUSCULA:
      convMayuscula();
      break;
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void convMinuscula() throws ParseException {
    jj_consume_token(MINUSCULA);
    jj_consume_token(PUNTO);
    jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASIGNACION:
      jj_consume_token(ASIGNACION);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIPO_DATO:
        jj_consume_token(TIPO_DATO);
        break;
      default:
        jj_la1[37] = jj_gen;
        ;
      }
      jj_consume_token(IDENTIFIER);
      break;
    default:
      jj_la1[38] = jj_gen;
      ;
    }
  }

  static final public void convMayuscula() throws ParseException {
    jj_consume_token(MAYUSCULA);
    jj_consume_token(PUNTO);
    jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASIGNACION:
      jj_consume_token(ASIGNACION);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIPO_DATO:
        jj_consume_token(TIPO_DATO);
        break;
      default:
        jj_la1[39] = jj_gen;
        ;
      }
      jj_consume_token(IDENTIFIER);
      break;
    default:
      jj_la1[40] = jj_gen;
      ;
    }
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public compiladorTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[41];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static private int[] jj_la1_4;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
      jj_la1_init_4();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x20000,0x200,0x0,0x100000,0x100000,0x8,0x600010,0x600010,0x40001e42,0x40001e42,0x0,0x0,0x0,0x20000000,0x1000000,0x0,0x0,0x0,0x200,0x1e42,0x1e42,0x200,0x10000,0x200,0x601e10,0x601e10,0x1400,0x0,0x10000,0x200,0x10000,0x10000,0x0,0x400010,0x200,0x0,0x200,0x800000,0x200,0x800000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x1000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1856,0x1856,0x0,0x4000,0x2000,0x0,0x0,0x0,0x20000,0x16,0x0,0x1016,0x1016,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x6c000020,0x6c000020,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc000020,0xc000020,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc000000,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2c,0x2c,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20,0x20,0x0,0x0,0x0,0xc,0xc,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_4() {
      jj_la1_4 = new int[] {0x0,0x0,0x0,0x4,0x800,0x800,0x0,0x0,0x0,0xe48,0xe48,0x1b800,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x800,0xc48,0xc48,0x800,0x0,0x0,0x0,0x0,0x0,0x9000,0x0,0x800,0x0,0x0,0x1800,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public compilador(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public compilador(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new compiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public compilador(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new compiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public compilador(compiladorTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(compiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[153];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 41; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
          if ((jj_la1_4[i] & (1<<j)) != 0) {
            la1tokens[128+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 153; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
